-- CREATE DATABASE 
CREATE DATABASE db_ibbakes;

-- TABLE FOR ACCOUNTS
CREATE TABLE tbl_users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
